import streamlit as st
import pandas as pd
from fpdf import FPDF
import base64
from datetime import datetime
import tempfile
import matplotlib.pyplot as plt
import matplotlib
matplotlib.use('Agg')
import os
import numpy as np

from .utils import format_indian_currency

# Wrapper for PDF compatibility (using Rs. instead of ₹ symbol if needed, or ensuring font support)
# For FPDF, unicode '₹' might be tricky without specific fonts. Let's use 'Rs.' for PDF.
def format_currency_pdf(value):
    return format_indian_currency(value, "Rs.")

class PDF(FPDF):
    def header(self):
        # Logo
        if os.path.exists("assets/logo.png"):
            self.image("assets/logo.png", 10, 8, 33)
        self.set_font('Arial', 'B', 15)
        # Move to right
        self.cell(80)
        self.cell(30, 10, 'Sales Performance Report', 0, 0, 'C')
        self.ln(20)

    def footer(self):
        self.set_y(-15)
        self.set_font('Arial', 'I', 8)
        self.cell(0, 10, f'Page {self.page_no()} | Generated by ELETTRO Intelligence', 0, 0, 'C')

def create_chart(fig):
    # Apply professional styling before saving
    for ax in fig.get_axes():
        ax.spines['top'].set_visible(False)
        ax.spines['right'].set_visible(False)
        ax.grid(True, linestyle='--', alpha=0.6, color='#dddddd')
        ax.tick_params(axis='both', which='major', labelsize=10)
        
    with tempfile.NamedTemporaryFile(delete=False, suffix=".png") as tmp:
        # High DPI for clear printing
        fig.savefig(tmp.name, bbox_inches='tight', dpi=300, facecolor='white')
        return tmp.name

def generate_pdf(df, report_type, specific_entity=None):
    pdf = PDF()
    pdf.alias_nb_pages()
    pdf.add_page()
    pdf.set_auto_page_break(auto=True, margin=15)
    
    # --- Context & Title ---
    title_text = f"Report: {report_type}"
    sub_title = "Fiscal Year Overview"
    
    # Filter Data
    if specific_entity and specific_entity != "All":
        if report_type == "Customer Wise":
            df = df[df["CUSTOMER_NAME"] == specific_entity]
        elif report_type == "City Wise":
            col = "CITY" if "CITY" in df.columns else "STATE"
            df = df[df[col] == specific_entity]
        elif report_type == "Material Wise":
            col = "ITEMNAME" if "ITEMNAME" in df.columns else "MATERIALGROUP"
            df = df[df[col] == specific_entity]
        elif report_type == "Material Group Wise":
            col = "ITEM_NAME_GROUP" if "ITEM_NAME_GROUP" in df.columns else "MATERIALGROUP"
            df = df[df[col] == specific_entity]
        title_text = f"Profile: {str(specific_entity)[:50]}"
        sub_title = f"{report_type} Deep Dive"
    
    # Ensure we work on a copy to avoid SettingWithCopyWarning
    df = df.copy()

    # --- Page 1: Executive Dashboard ---
    
    # 1. Title Area
    pdf.set_font("Arial", 'B', 16)
    pdf.cell(0, 10, title_text, 0, 1, 'L')
    pdf.set_font("Arial", 'I', 10)
    pdf.cell(0, 5, f"{sub_title} | Generated: {datetime.now().strftime('%d-%b-%Y')}", 0, 1, 'L')
    pdf.line(10, 40, 200, 40)
    pdf.ln(10)

    # 2. KPI Grid
    total_rev = df["AMOUNT"].sum()
    total_orders = df["INVOICE_NO"].nunique()
    total_qty = df["QUANTITY"].sum() if "QUANTITY" in df.columns else 0
    avg_order = total_rev / total_orders if total_orders > 0 else 0

    pdf.set_font("Arial", 'B', 12)
    pdf.cell(0, 10, "1. Executive Summary", 0, 1)
    
    # Draw KPI Box
    pdf.set_fill_color(245, 245, 245)
    pdf.rect(10, pdf.get_y(), 190, 25, 'F')
    pdf.set_y(pdf.get_y() + 5)
    
    pdf.set_font("Arial", 'B', 10)
    start_x = pdf.get_x()
    
    pdf.cell(45, 5, "Total Revenue", 0, 0, 'C')
    pdf.cell(45, 5, "Total Orders", 0, 0, 'C')
    pdf.cell(45, 5, "Total Quantity", 0, 0, 'C')
    pdf.cell(45, 5, "Avg Order Value", 0, 1, 'C')
    
    pdf.set_font("Arial", '', 12)
    pdf.set_text_color(0, 100, 0) # Dark Green for numbers
    pdf.cell(45, 10, format_currency_pdf(total_rev), 0, 0, 'C')
    pdf.set_text_color(0, 0, 0)
    pdf.cell(45, 10, f"{total_orders:,}", 0, 0, 'C')
    pdf.cell(45, 10, f"{int(total_qty):,}", 0, 0, 'C')
    pdf.cell(45, 10, format_currency_pdf(avg_order), 0, 1, 'C')
    pdf.ln(10)

    # 3. Monthly Trend Graph
    if "MONTH" in df.columns:
        trend = df.groupby("MONTH")["AMOUNT"].sum().reset_index()
        
        # Sort chronologically
        try:
            trend["SortKey"] = pd.to_datetime(trend["MONTH"], format="%b-%y", errors='coerce')
            trend = trend.sort_values("SortKey")
        except:
            pass
            
        fig, ax = plt.subplots(figsize=(10, 4))
        ax.plot(trend["MONTH"], trend["AMOUNT"], marker='o', color='#FFD700', linewidth=2)
        ax.set_title("Monthly Revenue Trend", fontsize=12, fontweight='bold')
        ax.grid(True, linestyle='--', alpha=0.5)
        ax.set_xlabel("Month")
        ax.set_ylabel("Revenue")
        
        img_path = create_chart(fig)
        plt.close(fig)
        
        pdf.set_font("Arial", 'B', 12)
        pdf.cell(0, 10, "2. Revenue Trend", 0, 1)
        pdf.image(img_path, x=10, w=190)
        os.remove(img_path)
        pdf.ln(5)

        fig, ax = plt.subplots(figsize=(10, 4))
        # Clear background
        fig.patch.set_facecolor('white')
        ax.set_facecolor('white')
        
        ax.plot(trend["MONTH"], trend["AMOUNT"], marker='o', color='#B8860B', linewidth=2.5, markersize=8) # Dark Goldenrod
        ax.set_title("Monthly Revenue Trend", fontsize=14, fontweight='bold', pad=15)
        ax.set_xlabel("Month", fontsize=11, fontweight='bold')
        ax.set_ylabel("Revenue", fontsize=11, fontweight='bold')
        
        # Rotate Labels 45 Degrees
        plt.setp(ax.get_xticklabels(), rotation=45, ha="right", rotation_mode="anchor")
        
        # Add data labels (skip overlapping ones if too many)
        step = 1 if len(trend) < 15 else 2
        for i, (x, y) in enumerate(zip(trend["MONTH"], trend["AMOUNT"])):
            if i % step == 0:
                label = format_currency_pdf(y)
                ax.annotate(label, 
                            (x, y), 
                            textcoords="offset points", 
                            xytext=(0,10), 
                            ha='center', 
                            fontsize=8,
                            bbox=dict(boxstyle="round,pad=0.3", fc="white", ec="#dddddd", alpha=0.8))
        
        img_path = create_chart(fig)
        plt.close(fig)
        
        pdf.set_font("Arial", 'B', 12)
        pdf.cell(0, 10, "2. Revenue Trend", 0, 1)
        pdf.image(img_path, x=10, w=190)
        os.remove(img_path)
        pdf.ln(5)

    # --- Page 2: Category Analysis with Donut Chart ---
    pdf.add_page()
    
    # 4. Material Group Analysis (Donut Chart)
    grp_col = "ITEM_NAME_GROUP" if "ITEM_NAME_GROUP" in df.columns else "MATERIALGROUP"
    if grp_col in df.columns:
        pdf.set_font("Arial", 'B', 12)
        pdf.cell(0, 10, "3. Category Distribution", 0, 1)
        
        # Prepare Data: Top 5 + Others
        grp_data = df.groupby(grp_col)["AMOUNT"].sum().sort_values(ascending=False)
        if len(grp_data) > 5:
            top_5 = grp_data.head(5)
            others = pd.Series([grp_data.iloc[5:].sum()], index=["Others"])
            final_data = pd.concat([top_5, others])
        else:
            final_data = grp_data

        fig, ax = plt.subplots(figsize=(10, 6))
        # Clear background
        fig.patch.set_facecolor('white')
        ax.set_facecolor('white')
        
        # Gold based colors
        colors = plt.cm.YlOrBr(np.linspace(0.4, 0.9, len(final_data)))
        
        # Donut Chart with filtered labels
        def autopct_format(pct):
            return ('%1.1f%%' % pct) if pct > 4 else ''

        wedges, texts, autotexts = ax.pie(final_data, autopct=autopct_format, startangle=90, 
                                          colors=colors, wedgeprops=dict(width=0.4, edgecolor='w'),
                                          textprops={'fontsize': 10, 'weight': 'bold'}, pctdistance=0.85)
        
        # Legend Side
        ax.legend(wedges, final_data.index, title="Categories", loc="center left", bbox_to_anchor=(1, 0, 0.5, 1), fontsize=9)
        ax.set_title(f"Revenue by {grp_col}", fontsize=14, fontweight='bold', pad=20)
        
        img_path = create_chart(fig)
        plt.close(fig)
        
        pdf.image(img_path, x=10, w=180)
        os.remove(img_path)
        pdf.ln(5)

    # 5. Top Performers (Bar Chart)
    pdf.set_font("Arial", 'B', 12)
    entity_label = "Items" if "ITEMNAME" in df.columns else "Products"
    pdf.cell(0, 10, f"4. Top 10 {entity_label}", 0, 1)
    
    col_item = "ITEMNAME" if "ITEMNAME" in df.columns else "MATERIALGROUP"
    top_items = df.groupby(col_item)["AMOUNT"].sum().sort_values(ascending=False).head(10)
    
    fig, ax = plt.subplots(figsize=(10, 5))
    # Clear background
    fig.patch.set_facecolor('white')
    ax.set_facecolor('white')
    
    # Horizontal Bar Chart
    container = top_items.sort_values().plot(kind='barh', color='#333333', edgecolor='#FFD700', width=0.7, ax=ax)
    
    ax.set_title(f"Top 10 {entity_label} by Revenue", fontsize=14, fontweight='bold', pad=15)
    ax.set_xlabel("Revenue (INR)", fontsize=11, fontweight='bold')
    ax.set_ylabel(None)
    
    # Add data labels inside bars or at end
    for container in ax.containers:
        ax.bar_label(container, fmt=lambda x: format_currency_pdf(x), padding=5, fontsize=9)
        
    plt.tight_layout()
    
    img_path = create_chart(fig)
    plt.close(fig)
    
    pdf.image(img_path, x=10, w=190)
    os.remove(img_path)
    pdf.ln(10)
    
    # 6. Detailed Table (Top 15)
    pdf.set_font("Arial", 'B', 12)
    pdf.cell(0, 10, "5. Detailed Breakdown", 0, 1)
    
    # Table Header
    pdf.set_font("Arial", 'B', 9)
    pdf.set_fill_color(220, 220, 220)
    pdf.cell(100, 8, "Item Description", 1, 0, 'L', 1)
    pdf.cell(45, 8, "Category", 1, 0, 'L', 1)
    pdf.cell(45, 8, "Revenue", 1, 1, 'R', 1)
    
    pdf.set_font("Arial", '', 8)
    # top 15 items for table
    detailed_data = df.groupby([col_item, grp_col])["AMOUNT"].sum().reset_index().sort_values(by="AMOUNT", ascending=False).head(25)
    
    for idx, row in detailed_data.iterrows():
        name = str(row[col_item])[:55]
        grp = str(row[grp_col])[:20]
        amt = format_currency_pdf(row["AMOUNT"])
        
        pdf.cell(100, 7, name, 1)
        pdf.cell(45, 7, grp, 1)
        pdf.cell(45, 7, amt, 1, 1, 'R')

    # --- Page 3: FY Analysis & Deep Dive ---
    pdf.add_page()
    
    # 7. FY Year-Over-Year Analysis
    if "FINANCIAL_YEAR" in df.columns:
        pdf.set_font("Arial", 'B', 14)
        pdf.cell(0, 10, "6. Fiscal Year (FY) Analysis", 0, 1)
        pdf.ln(2)

        # FY Summary Table
        fy_stats = df.groupby("FINANCIAL_YEAR").agg(
            Revenue=("AMOUNT", "sum"),
            Orders=("INVOICE_NO", "nunique")
        ).sort_index()

        pdf.set_font("Arial", 'B', 10)
        pdf.set_fill_color(240, 240, 240)
        pdf.cell(40, 8, "Fiscal Year", 1, 0, 'C', 1)
        pdf.cell(50, 8, "Total Revenue", 1, 0, 'C', 1)
        pdf.cell(40, 8, "Total Orders", 1, 0, 'C', 1)
        pdf.cell(50, 8, "YoY Growth", 1, 1, 'C', 1)
        
        pdf.set_font("Arial", '', 10)
        prev_rev = 0
        for fy, row in fy_stats.iterrows():
            growth = ((row['Revenue'] - prev_rev) / prev_rev * 100) if prev_rev > 0 else 0
            growth_str = f"{growth:+.1f}%" if prev_rev > 0 else "-"
            
            pdf.cell(40, 8, fy, 1, 0, 'C')
            pdf.cell(50, 8, format_currency_pdf(row['Revenue']), 1, 0, 'R')
            pdf.cell(40, 8, str(row['Orders']), 1, 0, 'C')
            pdf.cell(50, 8, growth_str, 1, 1, 'C')
            prev_rev = row['Revenue']
        pdf.ln(5)

        # FY Comparison Chart (Multi-line)
        if "MONTH" in df.columns:
            # Create a pivot table for charting
            # We need Month Name (order) vs Revenue, Hue = FY
            # Extract month number/name for sorting
            df['Month_Num'] = pd.to_datetime(df['DATE']).dt.month
            df['Month_Name'] = pd.to_datetime(df['DATE']).dt.strftime('%b')
            
            # Aggregate
            fy_trend = df.groupby(['FINANCIAL_YEAR', 'Month_Num', 'Month_Name'])['AMOUNT'].sum().reset_index()
            # Sort by Month Num
            fy_trend.sort_values('Month_Num', inplace=True)
            
            fig, ax = plt.subplots(figsize=(10, 5))
            # Clear background
            fig.patch.set_facecolor('white')
            ax.set_facecolor('white')
            
            # Plot each FY as a separate line
            for fy in fy_trend['FINANCIAL_YEAR'].unique():
                data = fy_trend[fy_trend['FINANCIAL_YEAR'] == fy]
                ax.plot(data['Month_Name'], data['AMOUNT'], marker='o', label=fy, linewidth=2.5, markersize=6)
            
            ax.set_title("Year-Over-Year Revenue Trends", fontsize=14, fontweight='bold', pad=15)
            ax.legend(fontsize=10)
            ax.set_xlabel("Month", fontsize=11, fontweight='bold')
            ax.set_ylabel("Revenue", fontsize=11, fontweight='bold')
            
            # Rotate labels if needed
            plt.xticks(rotation=45)
            
            img_path = create_chart(fig)
            plt.close(fig)
            pdf.image(img_path, x=10, w=190)
            os.remove(img_path)
            pdf.ln(5)

    # 8. Material Group Deep Dive
    pdf.set_font("Arial", 'B', 14)
    pdf.cell(0, 10, "7. Material Group Deep Dive", 0, 1)
    pdf.ln(5)

    # Get data by group
    if grp_col in df.columns:
        group_summary = df.groupby(grp_col).agg(
            Total_Revenue=("AMOUNT", "sum"),
            Top_Item=(col_item, lambda x: x.mode()[0] if not x.mode().empty else "N/A"),
            Order_Count=("INVOICE_NO", "nunique")
        ).sort_values(by="Total_Revenue", ascending=False).head(8) # Top 8 groups to fit on page
        
        for group_name, row in group_summary.iterrows():
            pdf.set_font("Arial", 'B', 11)
            pdf.set_fill_color(240, 240, 240)
            pdf.cell(0, 8, f"{group_name}", 0, 1, 'L', 1)
            
            pdf.set_font("Arial", '', 10)
            rev_share = (row["Total_Revenue"] / total_rev) * 100
            
            details = (f"Revenue: {format_currency_pdf(row['Total_Revenue'])} ({rev_share:.1f}% Share) | "
                       f"Orders: {row['Order_Count']} | "
                       f"Best Seller: {str(row['Top_Item'])[:40]}")
            
            pdf.cell(0, 8, details, 0, 1)
            pdf.ln(2)

    # 9. Customer Specific Enhancement: Material Group Preference
    if report_type == "Customer Wise":
        pdf.add_page()
        pdf.set_font("Arial", 'B', 14)
        pdf.cell(0, 10, "8. Material Group Preference", 0, 1)
        pdf.ln(5)
        
        # Group by Material Group
        mat_grp_data = df.groupby(grp_col)["AMOUNT"].sum().sort_values(ascending=False).head(15)
        
        pdf.set_font("Arial", 'B', 10)
        pdf.set_fill_color(240, 240, 240)
        pdf.cell(120, 8, "Material Group", 1, 0, 'L', 1)
        pdf.cell(50, 8, "Revenue", 1, 1, 'R', 1)
        
        pdf.set_font("Arial", '', 10)
        for grp, amt in mat_grp_data.items():
            pdf.cell(120, 8, str(grp)[:60], 1, 0, 'L')
            pdf.cell(50, 8, format_currency_pdf(amt), 1, 1, 'R')

    # 10. Material Group Specific Enhancement: Top Customers
    if report_type == "Material Group Wise":
        pdf.add_page()
        pdf.set_font("Arial", 'B', 14)
        pdf.cell(0, 10, "8. Top 10 Customers", 0, 1)
        pdf.ln(5)
        
        # Group by Customer
        cust_data = df.groupby("CUSTOMER_NAME")["AMOUNT"].sum().sort_values(ascending=False).head(15)
        
        pdf.set_font("Arial", 'B', 10)
        pdf.set_fill_color(240, 240, 240)
        pdf.cell(120, 8, "Customer Name", 1, 0, 'L', 1)
        pdf.cell(50, 8, "Revenue", 1, 1, 'R', 1)
        
        pdf.set_font("Arial", '', 10)
        for cust, amt in cust_data.items():
            pdf.cell(120, 8, str(cust)[:60], 1, 0, 'L')
            pdf.cell(50, 8, format_currency_pdf(amt), 1, 1, 'R')

    return pdf

def render_reporting(df):
    st.subheader("📄 Industrial Executive Reporting")
    st.caption("Generate premium industrial-grade sales reports with Fiscal Year context.")
    
    c1, c2 = st.columns(2)
    with c1:
        report_type = st.selectbox("Report Type:", ["Customer Wise", "City Wise", "Material Wise", "Material Group Wise"])
    with c2:
        # Dynamic Filter
        options = ["All"]
        if report_type == "Customer Wise":
            options += sorted(df["CUSTOMER_NAME"].unique().tolist())
        elif report_type == "City Wise":
            col = "CITY" if "CITY" in df.columns else "STATE"
            options += sorted(df[col].dropna().unique().tolist())
        elif report_type == "Material Wise":
            col = "ITEMNAME" if "ITEMNAME" in df.columns else "MATERIALGROUP"
            options += sorted(df[col].dropna().unique().tolist())
        elif report_type == "Material Group Wise":
            col = "ITEM_NAME_GROUP" if "ITEM_NAME_GROUP" in df.columns else "MATERIALGROUP"
            options += sorted(df[col].dropna().unique().tolist())
            
        specific_entity = st.selectbox("Specific Entity (Optional):", options)

    if st.button("Generate Industrial PDF Report"):
        fname_entity = specific_entity if specific_entity != "All" else "Summary"
        with st.spinner("Generating Professional Report..."):
            try:
                pdf = generate_pdf(df, report_type, specific_entity)
                
                pdf_output = pdf.output(dest='S').encode('latin-1')
                b64 = base64.b64encode(pdf_output).decode()
                filename = f"ELETTRO_Industrial_Report_{fname_entity}.pdf"
                
                href = f'<a href="data:application/octet-stream;base64,{b64}" download="{filename}">' \
                       f'<button style="background-color:#333; color:#FFD700; border:2px solid #FFD700; padding:12px 24px; border-radius:5px; font-weight:bold; width:100%;">' \
                       f'⬇️ Download Industrial Report</button></a>'
                st.markdown(href, unsafe_allow_html=True)
                st.success("Report Ready!")
            except Exception as e:
                st.error(f"Error: {e}")
