import streamlit as st
import pandas as pd
from fpdf import FPDF
import base64
from datetime import datetime
import tempfile
import matplotlib.pyplot as plt
import matplotlib
matplotlib.use('Agg')
import os
import numpy as np

from .utils import format_indian_currency

# --- Data Analysis Helpers ---

def classify_categories(df, grp_col="ITEM_NAME_GROUP"):
    """
    Classifies categories into High, Medium, Low value based on revenue.
    High: Top 70% cumulative value
    Medium: Next 20%
    Low: Bottom 10%
    """
    if grp_col not in df.columns:
        return pd.DataFrame()
        
    stats = df.groupby(grp_col).agg(
        Revenue=("AMOUNT", "sum"),
        Orders=("INVOICE_NO", "nunique")
    ).sort_values("Revenue", ascending=False)
    
    total_rev = stats["Revenue"].sum()
    stats["Share"] = (stats["Revenue"] / total_rev) * 100
    stats["CumShare"] = stats["Share"].cumsum()
    
    def get_class(cum_share):
        if cum_share <= 70: return "High Value"
        elif cum_share <= 90: return "Medium Value"
        else: return "Low Value"
        
    stats["Classification"] = stats["CumShare"].apply(get_class)
    
    # Correction: distinct cutoffs might put one item in High that bridges the gap.
    # Logic is fine for approximation.
    return stats

def analyze_consolidation(df, grp_col="ITEM_NAME_GROUP"):
    """
    Identifies Low Value categories with high order frequency (Fragmented).
    """
    if grp_col not in df.columns:
        return pd.DataFrame()
        
    stats = classify_categories(df, grp_col)
    if stats.empty: return stats
    
    # Filter for Low/Medium Value but High Frequency (e.g. above avg orders)
    avg_orders = stats["Orders"].mean()
    potential = stats[
        (stats["Classification"].isin(["Low Value", "Medium Value"])) & 
        (stats["Orders"] > avg_orders)
    ].copy()
    
    potential["Avg_Order_Value"] = potential["Revenue"] / potential["Orders"]
    return potential.sort_values("Orders", ascending=False)


# Wrapper for PDF compatibility (using Rs. instead of ₹ symbol if needed, or ensuring font support)
# For FPDF, unicode '₹' might be tricky without specific fonts. Let's use 'Rs.' for PDF.
def format_currency_pdf(value):
    return format_indian_currency(value, "Rs.")

class PDF(FPDF):
    def header(self):
        # Executive Header Strip
        self.set_fill_color(33, 33, 33) # Dark Grey Background
        self.rect(0, 0, 210, 20, 'F')
        
        # Gold Accent Line
        self.set_fill_color(255, 215, 0) # Gold
        self.rect(0, 19, 210, 1, 'F')
        
        # Company Name / Logo
        self.set_font('Arial', 'B', 12)
        self.set_text_color(255, 255, 255)
        self.set_xy(10, 5)
        self.cell(0, 10, 'ELETTRO INTELLIGENCE', 0, 0, 'L')
        
        # Report Title Placeholder (will be set dynamically if possible, but static here generally works)
        # We can't easily pass variable data to header() without class props, so we keep it generic or rely on body title.
        self.set_font('Arial', '', 10)
        self.set_xy(0, 5)
        self.cell(200, 10, 'Executive Sales Report', 0, 0, 'R')
        
        self.ln(25) # Move cursor down below header

    def footer(self):
        self.set_y(-15)
        self.set_font('Arial', 'I', 8)
        self.set_text_color(128, 128, 128)
        self.cell(0, 10, f'CONFIDENTIAL | Page {self.page_no()} | Generated by ELETTRO Intelligence', 0, 0, 'C')

    def create_cover_page(self, customer_name, fy_list):
        self.add_page()
        
        # 1. Background Design (Right Strip)
        self.set_fill_color(33, 33, 33)
        self.rect(140, 0, 70, 297, 'F')
        
        self.set_fill_color(255, 215, 0) # Gold
        self.rect(138, 0, 2, 297, 'F')
        
        # 2. Main Title Area
        self.set_xy(10, 80)
        self.set_font("Arial", 'B', 32)
        self.set_text_color(33, 37, 41)
        self.multi_cell(120, 14, "DISTRIBUTOR\nSTRATEGY\nREPORT", 0, 'L')
        
        # 3. Subtitle / Customer Name
        self.ln(10)
        self.set_font("Arial", '', 16)
        self.set_text_color(100, 100, 100)
        self.cell(120, 10, "PREPARED FOR:", 0, 1)
        
        self.set_font("Arial", 'B', 20)
        self.set_text_color(218, 165, 32) # Dark Gold
        self.multi_cell(120, 10, str(customer_name).upper(), 0, 'L')
        
        # 4. Financial Year Context
        self.ln(10)
        self.set_font("Arial", '', 12)
        self.set_text_color(33, 33, 33)
        fy_str = " | ".join(fy_list)
        self.cell(120, 10, f"Analysis Period: {fy_str}", 0, 1)
        self.cell(120, 8, f"Generated: {datetime.now().strftime('%d %B %Y')}", 0, 1)
        
        # 5. Big Logo (if available) or Text in Dark Strip
        # Ideally upload a logo image here. For now text.
        self.set_xy(150, 120)
        self.set_text_color(255, 255, 255)
        self.set_font("Arial", 'B', 24)
        self.multi_cell(50, 12, "ELETTRO\nINTELLIGENCE", 0, 'R')
        
        self.set_xy(150, 250)
        self.set_font("Arial", '', 10)
        self.multi_cell(50, 5, "Strictly Private & Confidential\n\nFor Management Use Only", 0, 'R')

def create_chart(fig):
    # Apply professional styling before saving
    for ax in fig.get_axes():
        ax.spines['top'].set_visible(False)
        ax.spines['right'].set_visible(False)
        ax.grid(True, linestyle='--', alpha=0.6, color='#dddddd')
        ax.tick_params(axis='both', which='major', labelsize=10)
        
    with tempfile.NamedTemporaryFile(delete=False, suffix=".png") as tmp:
        # High DPI for clear printing
        fig.savefig(tmp.name, bbox_inches='tight', dpi=300, facecolor='white')
        return tmp.name

def generate_pdf(df, report_type, specific_entity=None):
    pdf = PDF()
    pdf.alias_nb_pages()
    pdf.add_page()
    pdf.set_auto_page_break(auto=True, margin=15)
    
    # --- Context & Title ---
    title_text = f"Report: {report_type}"
    sub_title = "Fiscal Year Overview"
    
    # Filter Data
    if specific_entity and specific_entity != "All":
        if report_type == "Customer Wise":
            df = df[df["CUSTOMER_NAME"] == specific_entity]
        elif report_type == "City Wise":
            col = "CITY" if "CITY" in df.columns else "STATE"
            df = df[df[col] == specific_entity]
        elif report_type == "Material Wise":
            col = "ITEMNAME" if "ITEMNAME" in df.columns else "MATERIALGROUP"
            df = df[df[col] == specific_entity]
        elif report_type == "Material Group Wise":
            col = "ITEM_NAME_GROUP" if "ITEM_NAME_GROUP" in df.columns else "MATERIALGROUP"
            df = df[df[col] == specific_entity]
        title_text = f"Profile: {str(specific_entity)[:50]}"
        sub_title = f"{report_type} Deep Dive"
    
    # Ensure we work on a copy to avoid SettingWithCopyWarning
    df = df.copy()

    # --- Page 1: Executive Dashboard ---
    
    # 1. Title Area
    pdf.set_text_color(33, 33, 33)
    pdf.set_font("Arial", 'B', 20)
    pdf.cell(0, 10, title_text.upper(), 0, 1, 'L')
    
    pdf.set_font("Arial", '', 11)
    pdf.set_text_color(100, 100, 100)
    pdf.cell(0, 8, f"{sub_title} | Generated: {datetime.now().strftime('%d %B %Y')}", 0, 1, 'L')
    pdf.ln(5)

    # 2. KPI Grid (Material Design Cards)
    total_rev = df["AMOUNT"].sum()
    total_orders = df["INVOICE_NO"].nunique()
    total_qty = df["QUANTITY"].sum() if "QUANTITY" in df.columns else 0
    avg_order = total_rev / total_orders if total_orders > 0 else 0

    pdf.set_font("Arial", 'B', 14)
    pdf.set_text_color(0, 0, 0)
    pdf.cell(0, 10, "1. Executive Summary", 0, 1)
    
    # Draw KPI Boxes (Simulated Cards)
    # We will use 4 columns
    col_width = 45
    box_height = 25
    y_start = pdf.get_y()
    
    metrics = [
        ("TOTAL REVENUE", format_currency_pdf(total_rev)),
        ("TOTAL ORDERS", f"{total_orders:,}"),
        ("TOTAL QUANTITY", f"{int(total_qty):,}"),
        ("AVG ORDER VALUE", format_currency_pdf(avg_order))
    ]
    
    for i, (label, value) in enumerate(metrics):
        x = 10 + (i * (col_width + 3)) # 3mm gap
        
        # Card Background (Light Grey)
        pdf.set_fill_color(248, 249, 250)
        pdf.rect(x, y_start, col_width, box_height, 'F')
        
        # Top Border (Gold)
        pdf.set_fill_color(218, 165, 32) # Goldenrod
        pdf.rect(x, y_start, col_width, 1, 'F')
        
        # Label
        pdf.set_xy(x, y_start + 4)
        pdf.set_font("Arial", 'B', 7)
        pdf.set_text_color(108, 117, 125) # Muted text
        pdf.cell(col_width, 5, label, 0, 0, 'C')
        
        # Value
        pdf.set_xy(x, y_start + 11)
        pdf.set_font("Arial", 'B', 11)
        pdf.set_text_color(33, 37, 41) # Dark text
        pdf.cell(col_width, 8, value, 0, 0, 'C')

    pdf.set_y(y_start + box_height + 10)

    # 3. Monthly Trend Graph
    if "MONTH" in df.columns:
        trend = df.groupby("MONTH")["AMOUNT"].sum().reset_index()
        
        # Sort chronologically
        try:
            trend["SortKey"] = pd.to_datetime(trend["MONTH"], format="%b-%y", errors='coerce')
            trend = trend.sort_values("SortKey")
        except:
            pass
            
        fig, ax = plt.subplots(figsize=(10, 4))
        ax.plot(trend["MONTH"], trend["AMOUNT"], marker='o', color='#FFD700', linewidth=2)
        ax.set_title("Monthly Revenue Trend", fontsize=12, fontweight='bold')
        ax.grid(True, linestyle='--', alpha=0.5)
        ax.set_xlabel("Month")
        ax.set_ylabel("Revenue")
        
        img_path = create_chart(fig)
        plt.close(fig)
        
        pdf.set_font("Arial", 'B', 12)
        pdf.cell(0, 10, "2. Revenue Trend", 0, 1)
        pdf.image(img_path, x=10, w=190)
        os.remove(img_path)
        pdf.ln(5)

        fig, ax = plt.subplots(figsize=(10, 4))
        # Clear background
        fig.patch.set_facecolor('white')
        ax.set_facecolor('white')
        
        ax.plot(trend["MONTH"], trend["AMOUNT"], marker='o', color='#B8860B', linewidth=2.5, markersize=8) # Dark Goldenrod
        ax.set_title("Monthly Revenue Trend", fontsize=14, fontweight='bold', pad=15)
        ax.set_xlabel("Month", fontsize=11, fontweight='bold')
        ax.set_ylabel("Revenue", fontsize=11, fontweight='bold')
        
        # Rotate Labels 45 Degrees
        plt.setp(ax.get_xticklabels(), rotation=45, ha="right", rotation_mode="anchor")
        
        # Add data labels (skip overlapping ones if too many)
        step = 1 if len(trend) < 15 else 2
        for i, (x, y) in enumerate(zip(trend["MONTH"], trend["AMOUNT"])):
            if i % step == 0:
                label = format_currency_pdf(y)
                ax.annotate(label, 
                            (x, y), 
                            textcoords="offset points", 
                            xytext=(0,10), 
                            ha='center', 
                            fontsize=8,
                            bbox=dict(boxstyle="round,pad=0.3", fc="white", ec="#dddddd", alpha=0.8))
        
        img_path = create_chart(fig)
        plt.close(fig)
        
        pdf.set_font("Arial", 'B', 12)
        pdf.cell(0, 10, "2. Revenue Trend", 0, 1)
        pdf.image(img_path, x=10, w=190)
        os.remove(img_path)
        pdf.ln(5)

    # --- Page 2: Category Analysis with Donut Chart ---
    pdf.add_page()
    
    # 4. Material Group Analysis (Donut Chart)
    grp_col = "ITEM_NAME_GROUP" if "ITEM_NAME_GROUP" in df.columns else "MATERIALGROUP"
    if grp_col in df.columns:
        pdf.set_font("Arial", 'B', 12)
        pdf.cell(0, 10, "3. Category Distribution", 0, 1)
        
        # Prepare Data: Top 5 + Others
        grp_data = df.groupby(grp_col)["AMOUNT"].sum().sort_values(ascending=False)
        if len(grp_data) > 5:
            top_5 = grp_data.head(5)
            others = pd.Series([grp_data.iloc[5:].sum()], index=["Others"])
            final_data = pd.concat([top_5, others])
        else:
            final_data = grp_data

        fig, ax = plt.subplots(figsize=(10, 6))
        # Clear background
        fig.patch.set_facecolor('white')
        ax.set_facecolor('white')
        
        # Gold based colors
        colors = plt.cm.YlOrBr(np.linspace(0.4, 0.9, len(final_data)))
        
        # Donut Chart with filtered labels
        def autopct_format(pct):
            return ('%1.1f%%' % pct) if pct > 4 else ''

        wedges, texts, autotexts = ax.pie(final_data, autopct=autopct_format, startangle=90, 
                                          colors=colors, wedgeprops=dict(width=0.4, edgecolor='w'),
                                          textprops={'fontsize': 10, 'weight': 'bold'}, pctdistance=0.85)
        
        # Legend Side
        ax.legend(wedges, final_data.index, title="Categories", loc="center left", bbox_to_anchor=(1, 0, 0.5, 1), fontsize=9)
        ax.set_title(f"Revenue by {grp_col}", fontsize=14, fontweight='bold', pad=20)
        
        img_path = create_chart(fig)
        plt.close(fig)
        
        pdf.image(img_path, x=10, w=180)
        os.remove(img_path)
        pdf.ln(5)

    # 5. Top Performers (Bar Chart)
    pdf.set_font("Arial", 'B', 12)
    entity_label = "Items" if "ITEMNAME" in df.columns else "Products"
    pdf.cell(0, 10, f"4. Top 10 {entity_label}", 0, 1)
    
    col_item = "ITEMNAME" if "ITEMNAME" in df.columns else "MATERIALGROUP"
    top_items = df.groupby(col_item)["AMOUNT"].sum().sort_values(ascending=False).head(10)
    
    fig, ax = plt.subplots(figsize=(10, 5))
    # Clear background
    fig.patch.set_facecolor('white')
    ax.set_facecolor('white')
    
    # Horizontal Bar Chart
    container = top_items.sort_values().plot(kind='barh', color='#333333', edgecolor='#FFD700', width=0.7, ax=ax)
    
    ax.set_title(f"Top 10 {entity_label} by Revenue", fontsize=14, fontweight='bold', pad=15)
    ax.set_xlabel("Revenue (INR)", fontsize=11, fontweight='bold')
    ax.set_ylabel(None)
    
    # Add data labels inside bars or at end
    for container in ax.containers:
        ax.bar_label(container, fmt=lambda x: format_currency_pdf(x), padding=5, fontsize=9)
        
    plt.tight_layout()
    
    img_path = create_chart(fig)
    plt.close(fig)
    
    pdf.image(img_path, x=10, w=190)
    os.remove(img_path)
    pdf.ln(10)
    
    # 6. Detailed Breakdown Table
    pdf.set_font("Arial", 'B', 14)
    pdf.cell(0, 10, "5. Detailed Breakdown", 0, 1)
    
    # Table Header (Dark Theme)
    pdf.set_font("Arial", 'B', 9)
    pdf.set_fill_color(33, 37, 41) # Dark Header
    pdf.set_text_color(255, 255, 255) # White Text
    pdf.cell(100, 10, "Item Description", 0, 0, 'L', 1)
    pdf.cell(45, 10, "Category", 0, 0, 'L', 1)
    pdf.cell(45, 10, "Revenue", 0, 1, 'R', 1)
    
    pdf.set_font("Arial", '', 9)
    pdf.set_text_color(0, 0, 0) # Reset to black
    
    # top 25 items for table
    detailed_data = df.groupby([col_item, grp_col])["AMOUNT"].sum().reset_index().sort_values(by="AMOUNT", ascending=False).head(25)
    
    fill = False
    for idx, row in detailed_data.iterrows():
        # Zebra Striping
        pdf.set_fill_color(248, 249, 250) if fill else pdf.set_fill_color(255, 255, 255)
        
        name = str(row[col_item])[:55]
        grp = str(row[grp_col])[:20]
        amt = format_currency_pdf(row["AMOUNT"])
        
        pdf.cell(100, 8, name, 0, 0, 'L', fill)
        pdf.cell(45, 8, grp, 0, 0, 'L', fill)
        pdf.cell(45, 8, amt, 0, 1, 'R', fill)
        fill = not fill
        
    pdf.ln(5)
    # Divider Line
    pdf.set_draw_color(200, 200, 200)
    pdf.line(10, pdf.get_y(), 200, pdf.get_y())
    pdf.ln(5)

    # --- Page 3: FY Analysis & Deep Dive ---
    pdf.add_page()
    
    # 7. FY Year-Over-Year Analysis
    if "FINANCIAL_YEAR" in df.columns:
        pdf.set_font("Arial", 'B', 14)
        pdf.cell(0, 10, "6. Fiscal Year (FY) Analysis", 0, 1)
        pdf.ln(2)

        # FY Summary Table
        fy_stats = df.groupby("FINANCIAL_YEAR").agg(
            Revenue=("AMOUNT", "sum"),
            Orders=("INVOICE_NO", "nunique")
        ).sort_index()

        pdf.set_font("Arial", 'B', 10)
        pdf.set_fill_color(33, 37, 41) # Dark Header
        pdf.set_text_color(255, 255, 255)
        pdf.cell(40, 10, "Fiscal Year", 0, 0, 'C', 1)
        pdf.cell(50, 10, "Total Revenue", 0, 0, 'C', 1)
        pdf.cell(40, 10, "Total Orders", 0, 0, 'C', 1)
        pdf.cell(50, 10, "YoY Growth", 0, 1, 'C', 1)
        
        pdf.set_font("Arial", '', 10)
        pdf.set_text_color(0, 0, 0)
        
        prev_rev = 0
        fill = False
        for fy, row in fy_stats.iterrows():
            # Zebra
            pdf.set_fill_color(248, 249, 250) if fill else pdf.set_fill_color(255, 255, 255)
            
            growth = ((row['Revenue'] - prev_rev) / prev_rev * 100) if prev_rev > 0 else 0
            growth_str = f"{growth:+.1f}%" if prev_rev > 0 else "-"
            
            pdf.cell(40, 8, fy, 0, 0, 'C', fill)
            pdf.cell(50, 8, format_currency_pdf(row['Revenue']), 0, 0, 'R', fill)
            pdf.cell(40, 8, str(row['Orders']), 0, 0, 'C', fill)
            pdf.cell(50, 8, growth_str, 0, 1, 'C', fill)
            prev_rev = row['Revenue']
            fill = not fill
        pdf.ln(5)

        # FY Comparison Chart (Multi-line)
        if "MONTH" in df.columns:
            # Create a pivot table for charting
            # We need Month Name (order) vs Revenue, Hue = FY
            # Extract month number/name for sorting
            df['Month_Num'] = pd.to_datetime(df['DATE']).dt.month
            df['Month_Name'] = pd.to_datetime(df['DATE']).dt.strftime('%b')
            
            # Aggregate
            fy_trend = df.groupby(['FINANCIAL_YEAR', 'Month_Num', 'Month_Name'])['AMOUNT'].sum().reset_index()
            # Sort by Month Num
            fy_trend.sort_values('Month_Num', inplace=True)
            
            fig, ax = plt.subplots(figsize=(10, 5))
            # Clear background
            fig.patch.set_facecolor('white')
            ax.set_facecolor('white')
            
            # Plot each FY as a separate line
            for fy in fy_trend['FINANCIAL_YEAR'].unique():
                data = fy_trend[fy_trend['FINANCIAL_YEAR'] == fy]
                ax.plot(data['Month_Name'], data['AMOUNT'], marker='o', label=fy, linewidth=2.5, markersize=6)
            
            ax.set_title("Year-Over-Year Revenue Trends", fontsize=14, fontweight='bold', pad=15)
            ax.legend(fontsize=10)
            ax.set_xlabel("Month", fontsize=11, fontweight='bold')
            ax.set_ylabel("Revenue", fontsize=11, fontweight='bold')
            
            # Rotate labels if needed
            plt.xticks(rotation=45)
            
            img_path = create_chart(fig)
            plt.close(fig)
            pdf.image(img_path, x=10, w=190)
            os.remove(img_path)
            pdf.ln(5)

    # 8. Material Group Deep Dive
    pdf.set_font("Arial", 'B', 14)
    pdf.cell(0, 10, "7. Material Group Deep Dive", 0, 1)
    pdf.ln(5)

    # Get data by group
    if grp_col in df.columns:
        group_summary = df.groupby(grp_col).agg(
            Total_Revenue=("AMOUNT", "sum"),
            Top_Item=(col_item, lambda x: x.mode()[0] if not x.mode().empty else "N/A"),
            Order_Count=("INVOICE_NO", "nunique")
        ).sort_values(by="Total_Revenue", ascending=False).head(8) # Top 8 groups to fit on page
        
        for group_name, row in group_summary.iterrows():
            pdf.set_font("Arial", 'B', 11)
            pdf.set_fill_color(33, 37, 41)
            pdf.set_text_color(255, 255, 255)
            pdf.cell(0, 8, f" {group_name}", 0, 1, 'L', 1)
            
            pdf.set_font("Arial", '', 10)
            pdf.set_text_color(0, 0, 0)
            
            rev_share = (row["Total_Revenue"] / total_rev) * 100
            
            # Details Row
            pdf.set_fill_color(248, 249, 250)
            details = (f" Revenue: {format_currency_pdf(row['Total_Revenue'])} ({rev_share:.1f}% Share) | "
                       f"Orders: {row['Order_Count']} | "
                       f"Best Seller: {str(row['Top_Item'])[:40]}")
            
            pdf.cell(0, 8, details, 0, 1, 'L', 1)
            pdf.ln(3)

    # 9. Customer Specific Enhancement: Material Group Preference
    if report_type == "Customer Wise":
        pdf.add_page()
        pdf.set_font("Arial", 'B', 14)
        pdf.cell(0, 10, "8. Material Group Preference", 0, 1)
        pdf.ln(5)
        
        # Group by Material Group
        mat_grp_data = df.groupby(grp_col)["AMOUNT"].sum().sort_values(ascending=False).head(15)
        
        pdf.set_font("Arial", 'B', 10)
        pdf.set_fill_color(33, 37, 41) # Dark Header
        pdf.set_text_color(255, 255, 255)
        pdf.cell(120, 10, "Material Group", 0, 0, 'L', 1)
        pdf.cell(50, 10, "Revenue", 0, 1, 'R', 1)
        
        pdf.set_font("Arial", '', 10)
        pdf.set_text_color(0, 0, 0)
        
        fill = False
        for grp, amt in mat_grp_data.items():
            # Zebra
            pdf.set_fill_color(248, 249, 250) if fill else pdf.set_fill_color(255, 255, 255)
            pdf.cell(120, 8, str(grp)[:60], 0, 0, 'L', fill)
            pdf.cell(50, 8, format_currency_pdf(amt), 0, 1, 'R', fill)
            fill = not fill

    # 10. Material Group Specific Enhancement: Top Customers
    if report_type == "Material Group Wise":
        pdf.add_page()
        pdf.set_font("Arial", 'B', 14)
        pdf.cell(0, 10, "8. Top 10 Customers", 0, 1)
        pdf.ln(5)
        
        # Group by Customer
        cust_data = df.groupby("CUSTOMER_NAME")["AMOUNT"].sum().sort_values(ascending=False).head(15)
        
        pdf.set_font("Arial", 'B', 10)
        pdf.set_fill_color(33, 37, 41) # Dark Header
        pdf.set_text_color(255, 255, 255)
        pdf.cell(120, 10, "Customer Name", 0, 0, 'L', 1)
        pdf.cell(50, 10, "Revenue", 0, 1, 'R', 1)
        
        pdf.set_font("Arial", '', 10)
        pdf.set_text_color(0, 0, 0)
        
        fill = False
        for cust, amt in cust_data.items():
            # Zebra
            pdf.set_fill_color(248, 249, 250) if fill else pdf.set_fill_color(255, 255, 255)
            pdf.cell(120, 8, str(cust)[:60], 0, 0, 'L', fill)
            pdf.cell(50, 8, format_currency_pdf(amt), 0, 1, 'R', fill)
            fill = not fill

    return pdf

def render_reporting(df):
    st.subheader("📄 Industrial Executive Reporting")
    st.caption("Generate premium industrial-grade sales reports with Fiscal Year context.")
    
    c1, c2 = st.columns(2)
    with c1:
        report_type = st.selectbox("Report Type:", ["Distributor Strategy Report", "Customer Wise", "City Wise", "Material Wise", "Material Group Wise"])
    with c2:
        # Dynamic Filter
        options = ["All"]
        fy_list = []
        
        if report_type == "Distributor Strategy Report":
            # For Strategy Report, we need Customer + Comparison Years
            options = sorted(df["CUSTOMER_NAME"].unique().tolist())
            if "FINANCIAL_YEAR" in df.columns:
                fy_options = sorted(df["FINANCIAL_YEAR"].unique().tolist())
                fy_list = st.multiselect("Select Financial Years for Comparison:", fy_options, default=fy_options)
            else:
                st.info("Financial Year data missing.")
                
        elif report_type == "Customer Wise":
            options += sorted(df["CUSTOMER_NAME"].unique().tolist())
        elif report_type == "City Wise":
            col = "CITY" if "CITY" in df.columns else "STATE"
            options += sorted(df[col].dropna().unique().tolist())
        elif report_type == "Material Wise":
            col = "ITEMNAME" if "ITEMNAME" in df.columns else "MATERIALGROUP"
            options += sorted(df[col].dropna().unique().tolist())
        elif report_type == "Material Group Wise":
            col = "ITEM_NAME_GROUP" if "ITEM_NAME_GROUP" in df.columns else "MATERIALGROUP"
            options += sorted(df[col].dropna().unique().tolist())
            
        specific_entity = st.selectbox("Specific Entity:", options)

    if st.button("Generate Industrial PDF Report"):
        fname_entity = specific_entity if specific_entity != "All" else "Summary"
        with st.spinner("Generating Professional Report..."):
            try:
                pdf = None
                if report_type == "Distributor Strategy Report":
                     if specific_entity == "All":
                         st.error("Please select a specific customer for Strategy Report.")
                     else:
                         pdf = generate_distributor_strategy_report(df, specific_entity, fy_list)
                else:
                    pdf = generate_pdf(df, report_type, specific_entity)
                
                if pdf:
                    pdf_output = pdf.output(dest='S').encode('latin-1')
                    b64 = base64.b64encode(pdf_output).decode()
                    filename = f"ELETTRO_{report_type.replace(' ', '_')}_{fname_entity}.pdf"
                    
                    href = f'<a href="data:application/octet-stream;base64,{b64}" download="{filename}">' \
                           f'<button style="background-color:#333; color:#FFD700; border:2px solid #FFD700; padding:12px 24px; border-radius:5px; font-weight:bold; width:100%;">' \
                           f'⬇️ Download Industrial Report</button></a>'
                    st.markdown(href, unsafe_allow_html=True)
                    st.success("Report Ready!")
            except Exception as e:
                st.error(f"Error: {e}")

def generate_distributor_strategy_report(df, customer_name, fy_list):
    """
    Generates a high-end strategy report for a specific customer.
    """
    pdf = PDF()
    pdf.alias_nb_pages()
    
    # Filter Data
    cust_df = df[df["CUSTOMER_NAME"] == customer_name].copy()
    if fy_list:
        if "FINANCIAL_YEAR" in cust_df.columns:
            cust_df = cust_df[cust_df["FINANCIAL_YEAR"].isin(fy_list)]
    
    if cust_df.empty:
        return None

    # 1. Cover Page
    pdf.create_cover_page(customer_name, fy_list)
    
    # 2. Executive Summary Page
    pdf.add_page()
    pdf.set_font("Arial", 'B', 16)
    pdf.cell(0, 10, "1. Executive Summary", 0, 1)
    pdf.ln(5)
    
    # Metrics
    total_rev = cust_df["AMOUNT"].sum()
    total_orders = cust_df["INVOICE_NO"].nunique()
    avg_order = total_rev / total_orders if total_orders > 0 else 0
    
    # Classification Analysis
    grp_col = "ITEM_NAME_GROUP" if "ITEM_NAME_GROUP" in cust_df.columns else "MATERIALGROUP"
    class_stats = classify_categories(cust_df, grp_col)
    
    high_val = class_stats[class_stats["Classification"] == "High Value"]
    med_val = class_stats[class_stats["Classification"] == "Medium Value"]
    low_val = class_stats[class_stats["Classification"] == "Low Value"]
    
    high_share = high_val["Share"].sum() if not high_val.empty else 0
    
    # Write Summary Text
    pdf.set_font("Arial", '', 11)
    pdf.multi_cell(0, 6, f"For the period analysis of {', '.join(fy_list)}, {customer_name} has generated a Total Revenue of {format_currency_pdf(total_rev)} across {total_orders} orders.", 0, 'L')
    pdf.ln(5)
    pdf.multi_cell(0, 6, f"Business Structure Analysis:\n- High Value Categories (Top 70%): {len(high_val)} categories contribute {high_share:.1f}% of business.\n- This indicates a {'concentrated' if len(high_val) < 5 else 'diversified'} portfolio reliance.", 0, 'L')
    pdf.ln(5)
    
    # 3. Category Matrix (High Value)
    pdf.set_font("Arial", 'B', 14)
    pdf.cell(0, 10, "2. Strategic Category Matrix", 0, 1)
    
    # Pareto Chart
    if not class_stats.empty:
        fig, ax = plt.subplots(figsize=(10, 5))
        # Clear background
        fig.patch.set_facecolor('white')
        ax.set_facecolor('white')
        
        # Color mapped by classification
        colors = class_stats["Classification"].map({
            "High Value": "#FFD700", # Gold
            "Medium Value": "#C0C0C0", # Silver
            "Low Value": "#CD7F32" # Bronze
        })
        
        # Handle missing colors if map fails (e.g. key missing)
        colors = colors.fillna("#333333")
        
        chart_data = class_stats.head(15)
        ax.bar(chart_data.index, chart_data['Revenue'], color=colors.head(15))
        
        ax.set_title("Top 15 Categories by Strategic Value", fontweight='bold')
        ax.set_ylabel("Revenue")
        ax.set_xlabel(None)
        plt.xticks(rotation=45, ha='right')
        plt.tight_layout()
        
        img_path = create_chart(fig)
        plt.close(fig)
        pdf.image(img_path, x=10, w=190)
        os.remove(img_path)
        pdf.ln(5)
    
    # 4. Consolidation Opportunities
    pdf.add_page()
    pdf.set_font("Arial", 'B', 16)
    pdf.cell(0, 10, "3. Consolidation Opportunities", 0, 1)
    pdf.set_font("Arial", '', 11)
    pdf.multi_cell(0, 6, "Identified categories with high order frequency but low average value. Bundling these can improve logistics efficiency.", 0, 'L')
    pdf.ln(5)
    
    opps = analyze_consolidation(cust_df, grp_col)
    if not opps.empty:
        # Table Header
        pdf.set_font("Arial", 'B', 10)
        pdf.set_fill_color(33, 37, 41)
        pdf.set_text_color(255, 255, 255)
        pdf.cell(80, 10, "Category (Fragmented)", 0, 0, 'L', 1)
        pdf.cell(40, 10, "Order Freq", 0, 0, 'C', 1)
        pdf.cell(40, 10, "Avg Value", 0, 0, 'R', 1)
        pdf.cell(30, 10, "Status", 0, 1, 'C', 1)
        
        pdf.set_font("Arial", '', 10)
        pdf.set_text_color(0, 0, 0)
        
        fill = False
        for grp, row in opps.head(10).iterrows():
            pdf.set_fill_color(248, 249, 250) if fill else pdf.set_fill_color(255, 255, 255)
            pdf.cell(80, 8, str(grp)[:40], 0, 0, 'L', fill)
            pdf.cell(40, 8, str(row['Orders']), 0, 0, 'C', fill)
            pdf.cell(40, 8, format_currency_pdf(row['Avg_Order_Value']), 0, 0, 'R', fill)
            pdf.cell(30, 8, row['Classification'], 0, 1, 'C', fill)
            fill = not fill
    else:
        pdf.multi_cell(0, 6, "No significant fragmentation detected. Ordering behavior appears optimized.", 0, 'L')

    # 5. Multi-Year View (if multiple years selected)
    if len(fy_list) > 1 and "FINANCIAL_YEAR" in cust_df.columns:
        pdf.add_page()
        pdf.set_font("Arial", 'B', 16)
        pdf.cell(0, 10, "4. Year-over-Year Growth Analysis", 0, 1)
        
        # FY Summary
        fy_summary = cust_df.groupby("FINANCIAL_YEAR")["AMOUNT"].sum()
        
        fig, ax = plt.subplots(figsize=(10, 5))
        fig.patch.set_facecolor('white')
        ax.set_facecolor('white')
        
        fy_summary.plot(kind='bar', color='#333333', edgecolor='#FFD700', ax=ax)
        ax.set_title("Revenue Growth by Financial Year", fontweight='bold')
        ax.set_ylabel("Revenue")
        plt.xticks(rotation=0)
        
        # Labels
        for container in ax.containers:
            ax.bar_label(container, fmt=lambda x: format_currency_pdf(x), padding=5)
            
        img_path = create_chart(fig)
        plt.close(fig)
        pdf.image(img_path, x=10, w=190)
        os.remove(img_path)

    return pdf
